import 'package:dart_pdf_package/src/audit/dto/audit_assessment_dto.dart';
import 'package:dart_pdf_package/src/utils/pdf/tb_pdf_helper.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';

import '../audit_pdf_constants.dart';

class AuditFooterSection extends StatelessWidget {
  final String? pageNo;
  final AuditAssessmentDto? auditAssessmentEntity;

  final auditPdfTextStyle = AuditPdfTextStyles();

  AuditFooterSection({
    this.pageNo,
    this.auditAssessmentEntity,
  });
  @override
  Widget build(Context context) {
    return Container(
      height: 60,
      padding: EdgeInsets.only(
        top: 20,
        right: AuditPdfPaddings.pageRightPadding.right,
        left: AuditPdfPaddings.pageLeftPadding.left,
      ),
      alignment: Alignment.topCenter,
      child: Row(children: [
        Expanded(
            flex: 1,
            child: Container(
              height: 10,
            )),
        Expanded(
            flex: 2,
            child: Container(
                alignment: Alignment.center,
                child: auditAssessmentEntity?.isSubscribed == 0
                    ? Text(
                        "Report generated by www.riskassessor.net",
                        // style: auditPdfTextStyle.urlTextStyle(),
                        style: TbPdfHelper().textStyleGenerator(
                          font: Theme.of(context).iconTheme.font,
                          color: AuditPdfColors.auditBlueLightColor,
                          fontSize: 10,
                        ),
                      )
                    : Container())),
        Expanded(
            flex: 1,
            child: Container(
              alignment: Alignment.centerRight,
              child: Text(
                "Page No:  $pageNo${getReferenceNumber()}",
                style: TbPdfHelper().textStyleGenerator(
                  font: Theme.of(context).header0.fontItalic,
                  color: AuditPdfColors.black,
                  fontSize: 8,
                ),
              ),
            )),
      ]),
    );
  }

  String getReferenceNumber() {
    if ((auditAssessmentEntity?.referenceNumber ?? "").isNotEmpty) {
      return " / ${auditAssessmentEntity?.referenceNumber ?? ''}";
    } else {
      return "";
    }
  }
}
