import 'package:dart_pdf_package/src/ms/dto/ms_assessment_dto.dart';
import 'package:dart_pdf_package/src/ms/pdf_generator/tb_ms_pdf_constants.dart';
import 'package:dart_pdf_package/src/utils/pdf/tb_pdf_helper.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';

/// use for showing page number
class MsFooterSection extends StatelessWidget {
  String? pageNumber;
  MsAssessmentDto? msAssessmentDto;

  MsFooterSection({this.pageNumber, this.msAssessmentDto});

  @override
  Widget build(Context context) {
    return Container(
      margin: TbMsPdfPaddings.marginForFooterSection,
      padding: TbMsPdfPaddings.rightAndLeftPadding,
      child: Row(
        // mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Expanded(
            flex: 1,
            child: Container(),
          ),
          Expanded(
              flex: 2,
              child: Container(
                  alignment: Alignment.bottomCenter,
                  child: msAssessmentDto?.isSubscribed == 0
                      ? Text(
                          "Report generated by www.riskassessor.net",
                          // style: auditPdfTextStyle.urlTextStyle(),
                          style: TbPdfHelper().textStyleGenerator(
                            font: Theme.of(context).header0.fontItalic,
                            color: TbMsPdfColors.msBlueThemeColor,
                            fontSize: 10,
                          ),
                        )
                      : Container())),
          Expanded(
            flex: 1,
            child: Container(
              alignment: Alignment.bottomRight,
              child: Text(
                "Page No :$pageNumber${getReferenceNumber()}",
                // style: msPdfTextStyle.pageNumberTextStyle(),
                style: TbPdfHelper().textStyleGenerator(
                  font: Theme.of(context).header0.fontItalic,
                  color: TbMsPdfColors.black,
                  fontSize: 8,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  String getReferenceNumber() {
    if ((msAssessmentDto?.referenceNumber ?? "").isNotEmpty) {
      return " / ${msAssessmentDto?.referenceNumber ?? ''}";
    } else {
      return "";
    }
  }
}
